@startuml "Paketabhängigkeiten"
' General
left to right direction
'top to bottom direction
skinparam linetype polyline
'skinparam linetype ortho
'skinparam nodesep 100
skinparam ranksep 100
skinparam shadowing false

legend bottom center
    = Legende
    | <#LightGreen>      | Medizininformatik-Initiative |
    | <#LightBlue>       | gematik GmbH |
    | <#LightPink>       | KBV / MIO42 GmbH |
    | <#Orange>          | DVMD e.V. |
    | <#MediumPurple>    | IHE International / Deutschland |
    | <size:20><U+21E2></size> | Abhängigkeitsbeziehung |
end legend

' MII
package "de.medizininformatikinitiative.kerndatensatz.dokument" as MiiDokument #LightGreen {
    class MII_PR_Dokument_Dokument
}
package "de.medizininformatikinitiative.kerndatensatz.fall" as MiiFall #LightGreen {
    class MII_PR_Fall_KontaktGesundheitseinrichtung
}
package "de.medizininformatikinitiative.kerndatensatz.person" as MiiPerson #LightGreen {
    class MII_PR_Person_Patient
    class MII_PR_Person_PatientPseudonymisiert
}

' Gematik
package "de.gematik.isik-dokumentenaustausch" as GematikIsik #LightBlue {
    class ISiKDokumentenMetadaten
}

' KBV MIO
package "kbv.basis" as KbvMio #LightPink {
    class KBV_PR_Base_DocumentReference
}

' IHE International
package "ihe.iti.mhd" as IheMhd #MediumPurple {
    class UnContainedComprehensiveDocumentReference
}
package "ihe.formatcode.fhir" as IheFormatCode #MediumPurple {
    enum IHE_FormatCode_vs
}
package "de.ihe-d.terminology" as IheTerminology #MediumPurple {
    enum IHEXDSclassCode
    enum IHEXDStypeCode
}

' DVMD e.V.
package "dvmd.kdl.r4" as DvmdKdl #Orange {
    enum ValueSetKDL {}
}

' Explizite Abhängigkeiten
MiiDokument -[dashed,thickness=2]u-> MiiFall : "context.encounter"
MiiDokument -[dashed,thickness=2]u-> MiiPerson : "subject"
MiiDokument -[dashed,thickness=2]u-> DvmdKdl : "type.coding"
MiiDokument -[dashed,thickness=2]u-> IheFormatCode : "content.format.code"
MiiDokument -[dashed,thickness=2]u-> IheTerminology : "content.format.code"

' Berücksichtigte Abhängigkeiten (Profile)
MiiDokument -[dashed,thickness=2,#DarkGrey]d-> GematikIsik : <color:DarkGrey>berücksichtigt</color>
MiiDokument -[dashed,thickness=2,#DarkGrey]d-> KbvMio : <color:DarkGrey>berücksichtigt</color>
MiiDokument -[dashed,thickness=2,#DarkGrey]d-> IheMhd : <color:DarkGrey>berücksichtigt</color>

' Transitive Abhängigkeiten
'GematikIsik -[dashed]-> IheFormatCode
'GematikIsik -[dashed]-> IheMhd
'GematikIsik -[dashed]-> IheTerminology
'GematikIsik -[dashed]-> DvmdKdl
@enduml