Mapping: MII_MAP_Dok
Source: MII_LM_Dok
Id: mii-map-dok
Title: "MII MAP Dokument"
Description: "MII Mappings Modul Dokument"
* Dokument                              ->  "DocumentReference"
  * Masteridentifikator                 ->  "DocumentReference.masterIdentifier"
  * Businessidentifikator               ->  "DocumentReference.identifier"
  * Dokumentenreferenzstatus            ->  "DocumentReference.status"
  * Dokumentenstatus                    ->  "DocumentReference.docStatus"
  * Dokumententyp                       ->  "DocumentReference.type"
  * Dokumentenkategorie                 ->  "DocumentReference.category"
  * Patient                             ->  "DocumentReference.subject"
  * Beschreibung                        ->  "DocumentReference.description"
  * Sicherheitsstufe                    ->  "DocumentReference.securityLabel"
  * Dokumentenbeziehung                 ->  "DocumentReference.relatesTo"
    * Beziehungstyp                     ->  "DocumentReference.relatesTo.code"
    * Beziehungsreferenz                ->  "DocumentReference.relatesTo.target"
  * Anhang                              ->  "DocumentReference.content"
    * Sprache                           ->  "DocumentReference.attachment.language"
    * Erstellungsdatum                  ->  "DocumentReference.attachment.creation"
    * Daten                             ->  "DocumentReference.attachment.data"
    * DokumentenUrl                     ->  "DocumentReference.attachment.url"
    * Dokumentenformat                  ->  "DocumentReference.attachment.contentType"
  * Kontext                             ->  "DocumentReference.context"
    * Gesundheitseinrichtungskontakt    ->  "DocumentReference.context.encounter"
    * Vorgang                           ->  "DocumentReference.context.event"
    * Fachgebiet                        ->  "DocumentReference.context.practiceSetting"
    * Dokumentationszeitraum            ->  "DocumentReference.context.period"
    * Einrichtungsart                   ->  "DocumentReference.context.facilityType"
