Logical: MII_LM_Dokument
Parent: Element
Id: mii-lm-dokument
Title: "MII LM Dokument"
Description: "MII Logical Model KDS-Modul Dokument"
* insert LM_Header($mii-lm-dokument)
* Dokument                              1..1    BackboneElement     "Dokument"                          "Klinisches Dokument inkl. Metadaten, Inhalt, Erzeugungskontext und Beziehungen"
  * Masteridentifikator                 0..1    Identifier          "Versionsspezifische Kennung"       "Versionsspezifische eindeutige Kennung, die dem Dokument durch die Dokumentenquelle zugewiesen wurde"
  * Businessidentifikator               0..1    Identifier          "Versionsunabhängige Kennung"       "Andere versionsunabhängige Kennung, die dem Dokument (z.B. durch weitere dokumentenverarbeitende Systeme) zugewiesen wurde"
  * Dokumentenreferenzstatus            1..1    code                "Status der Dokumentenreferenz"     "Status dieser Dokumentenreferenz (aktuell, überholt oder irrtümlich eingegeben)"
  * Dokumentenstatus                    0..1    code                "Status des Dokuments"              "Status des zugrunde liegenden Dokuments (vorläufig, final, geändert oder irrtümlich eingegeben)"
  * Dokumententyp                       0..1    code                "Art des Dokuments"                 "Art des Dokuments auf das verwiesen wird (z.B. Anamnese und Untersuchung, Entlassungsbericht, Verlaufsbericht)"
  * Dokumentenkategorie                 0..*    code                "Kategorien des Dokuments"          "Übergeordnete Kategorie des Dokuments auf das verwiesen wird (z.B. Arztberichte oder Arztdokumentation)"
  * Patient                             0..1    Identifier          "Verweis auf Patient"               "Patient auf den sich das verwiesene Dokument bezieht"
  * Beschreibung                        0..1    string              "Beschreibung des Dokuments"        "Menschenlesbare Beschreibung zum verwiesenen Dokuments"
  * Sicherheitsstufe                    0..*    code                "Vertraulichkeit des Dokuments"     "Grad der Vertraulichkeit/Sicherheit des verwiesenen Dokuments (z. B. uneingeschränkt, gering, mittel, normal oder eingeschränkt)"
  * Dokumentenbeziehung                 0..*    BackboneElement     "Beziehung des Dokuments"           "Beziehungen des verwiesenen Dokuments zu anderen Dokumenten"
    * Beziehungstyp                     1..1    code                "Art der Beziehung"                 "Beziehung zu anderen Dokumenten"
    * Beziehungsreferenz                1..1    Identifier          "Verweis auf Dokument"              "Ziel der Dokumentenbeziehung"
  * Anhang                              1..*    BackboneElement     "Inhalt des Dokuments"              "Dokument (Base64-kodierte Daten) oder Verweis (URL) mit relevanten Metadaten zum Anhang"
    * Sprache                           0..1    code                "Verfassungssprache des Inhalts"    "Verwendete Sprache in dem Dokument"
    * Erstellungsdatum                  0..1    dateTime            "Erstellungsdatum des Inhalts"      "Datum der Erstellung des Dokumentes"
    * Daten                             0..1    base64Binary        "Binärdaten zum Inhalt"             "Dokument als Binärdaten"
    * DokumentenUrl                     0..1    string              "URL zum Inhalt"                    "Verweis auf den (lokalen) Ablageort des Dokuments"
    * Dokumentenformat                  0..1    code                "MIME-Typ zum Inhalt"               "MIME-Typ des Dokumenteninhalts"
  * Kontext                             0..1    BackboneElement     "Erzeugungskontext des Dokuments"   "Klinischer Kontext, in welchem das Dokument erzeugt wurde"
    * Gesundheitseinrichtungskontakt    0..*    Identifier          "Verweis auf Einrichtungskontakt"   "Kontakt zur Gesundheitseinrichtung oder die Art der Versorgung, die mit dem Dokumenteninhalt assoziiert ist"
    * Vorgang                           0..*    code                "Dokumentierter Vorgang"            "Handlungen oder Prozeduren, die im Kontext dokumentiert wurden"
    * Fachgebiet                        0..1    code                "Klinisches Fachgebiet zum Vorgang" "Klinisches Fachgebiet, in dem Dokumenteninhalt erstellt wurde"
    * Dokumentationszeitraum            0..1    Period              "Durchführungszeitraum zum Vorgang" "Zeitraum, in dem die in dem Dokument beschriebene Handlung oder Prozedur durchgeführt wurde"
    * Einrichtungsart                   0..1    code                "Art der Einrichtung zum Vorgang"   "Art der Einrichtung, in der die Handlung oder Prozedur am Patienten erfolgte"